<?php

namespace Camael\Bundle\MuscuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppartusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
